export const imagesAndHashes = [
  { src: "/images/1.jpg", hash: "T8Dub~AIIo0Q$ij?MboJoL~AbIay" },
  { src: "/images/2.jpg", hash: "T360p^DAra?;RRt5V1RRMhpFH^nl" },
  { src: "/images/3.jpg", hash: "TgNT,o_3t8_ND%Rj%Mofodxuogax" },
  { src: "/images/4.jpg", hash: "TcEolWj[M{_4jtaetmj[WqWBfkoz" },
  { src: "/images/5.jpg", hash: "TuPY@wRjxa~qjYM{Nbj[WBM{a}xu" },
  { src: "/images/6.jpg", hash: "TcNJX~7gO=?^jDV@B6M|spV]sVag" },
  { src: "/images/7.jpg", hash: "T55}HrI;0h0#xF}?$%WVNa-TWVEN" },
  { src: "/images/8.jpg", hash: "TKRCJTtl.T%~V@Q,v$j]IpRPj@x]" },
  { src: "/images/9.jpg", hash: "T2PE5v=;#m*Mk:S4.rItNcM%M#~7" },
  { src: "/images/10.jpg", hash: "TkNl=N=eb^D3I;wcR+n%I:NFsos:" },
  { src: "/images/11.jpg", hash: "T9FN6c$$58|@WVJ804R+xaENoL$%" },
  { src: "/images/12.jpg", hash: "TOGaRj~BoM0eR*ofE2ELR*xuR*Rj" },
  { src: "/images/13.jpg", hash: "T7AMbs?bJ600enj?}sRj+]12Na+u" },
  { src: "/images/14.jpg", hash: "TqEM:*xut7_Noej[ofRjRjM{WBWA" },
  { src: "/images/15.jpg", hash: "TORnoQYR}g?tw@M{xBN2J=s%oIoM" },
  { src: "/images/16.jpg", hash: "T4MaV5000c8w0|8C00_L9ZCiML+L" },
];
